apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-crypto-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: crypto-api # <--- ALTERADO DE crypto-app PARA crypto-api
 #O selector deve bater exatamente com o que esta no Deployment (crypto-api):    
